-- MySQL Script generated by MySQL Workbench
-- Wed Jun  4 11:35:54 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clients` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NOT NULL,
  `Cognoms` VARCHAR(45) NOT NULL,
  `Adreça` VARCHAR(45) NOT NULL,
  `C.P.` INT NOT NULL,
  `Localitat` VARCHAR(45) NOT NULL,
  `Provincia` VARCHAR(45) NOT NULL,
  `Telefon` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `Nom_UNIQUE` (`Nom` ASC) VISIBLE,
  UNIQUE INDEX `Cognoms_UNIQUE` (`Cognoms` ASC) VISIBLE,
  UNIQUE INDEX `Adreça_UNIQUE` (`Adreça` ASC) VISIBLE,
  UNIQUE INDEX `Telefon_UNIQUE` (`Telefon` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Categories` (
  `Categories` ENUM('a', 'b', 'c', 'd') NOT NULL,
  `parent_ID` INT NULL,
  `IdCategories` INT NULL AUTO_INCREMENT,
  PRIMARY KEY (`IdCategories`),
  INDEX `fk_Categoria_Parent_idx` (`parent_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Categoria_Parent`
    FOREIGN KEY (`parent_ID`)
    REFERENCES `mydb`.`Categories` (`IdCategories`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`botigues`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`botigues` (
  `Id_botiga` INT NOT NULL,
  `Nom` VARCHAR(45) NOT NULL,
  `Adreça` VARCHAR(45) NOT NULL,
  `C.P.` INT NOT NULL,
  `Provincia` VARCHAR(45) NOT NULL,
  `Localitat` VARCHAR(45) NOT NULL,
  `Comandes_Id_Comanda` INT NOT NULL,
  PRIMARY KEY (`Id_botiga`),
  UNIQUE INDEX `Comandes_Id_Comanda_UNIQUE` (`Comandes_Id_Comanda` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Productes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Productes` (
  `Id_Producte` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NOT NULL,
  `Descripcio` VARCHAR(45) NOT NULL,
  `Imatge` VARCHAR(45) NOT NULL,
  `Preu` FLOAT NOT NULL,
  `categoria_ID` INT NULL,
  PRIMARY KEY (`Id_Producte`),
  UNIQUE INDEX `Id_Producte_UNIQUE` (`Id_Producte` ASC) VISIBLE,
  INDEX `categoria_id_idx` (`categoria_ID` ASC) VISIBLE,
  CONSTRAINT `categoria_id`
    FOREIGN KEY (`categoria_ID`)
    REFERENCES `mydb`.`Categories` (`IdCategories`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comandes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Comandes` (
  `id_clients` INT NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `Tipus` ENUM('repartiment', 'domicili') NOT NULL,
  `Total_preu` VARCHAR(45) NOT NULL,
  `Repartidor` VARCHAR(45) NULL,
  `Data_comanda` DATETIME NOT NULL,
  `Data_entrega` DATETIME NOT NULL,
  `Quantitat Pizzes` INT NULL,
  `Quantitat Hamburguesa` INT NULL,
  `Quantitat Begudes` INT NULL,
  `botigues_Id_botiga` INT NOT NULL,
  `botigues_Comandes_Id_Comanda` INT NOT NULL,
  `id_producto` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Id_Comanda_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Clients_ID_idx` (`id_clients` ASC) VISIBLE,
  INDEX `fk_Quantitat_pizzes_idx` (`Quantitat Pizzes` ASC) VISIBLE,
  INDEX `fk_Quantitat_Hamburgueses_idx` (`Quantitat Hamburguesa` ASC) VISIBLE,
  INDEX `fk_Quantitat_Begudes_idx` (`Quantitat Begudes` ASC) VISIBLE,
  INDEX `fk_Comandes_botigues1_idx` (`botigues_Id_botiga` ASC, `botigues_Comandes_Id_Comanda` ASC) VISIBLE,
  INDEX `fk_id_producto_idx` (`id_producto` ASC) VISIBLE,
  CONSTRAINT `fk_Clients_ID`
    FOREIGN KEY (`id_clients`)
    REFERENCES `mydb`.`Clients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Quantitat_pizzes`
    FOREIGN KEY (`Quantitat Pizzes`)
    REFERENCES `mydb`.`Categories` (`IdCategories`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Quantitat_Hamburgueses`
    FOREIGN KEY (`Quantitat Hamburguesa`)
    REFERENCES `mydb`.`Categories` (`IdCategories`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Quantitat_Begudes`
    FOREIGN KEY (`Quantitat Begudes`)
    REFERENCES `mydb`.`Categories` (`IdCategories`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comandes_botigues1`
    FOREIGN KEY (`botigues_Id_botiga` , `botigues_Comandes_Id_Comanda`)
    REFERENCES `mydb`.`botigues` (`Id_botiga` , `Comandes_Id_Comanda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_producto`
    FOREIGN KEY (`id_producto`)
    REFERENCES `mydb`.`Productes` (`Id_Producte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empleats` (
  `Id_empleat` INT NOT NULL,
  `Nom` VARCHAR(45) NOT NULL,
  `Cognoms` VARCHAR(45) NOT NULL,
  `NIF` VARCHAR(45) NOT NULL,
  `Telefon` INT NOT NULL,
  `Rol` ENUM('Cuiner', 'Repartidor') NOT NULL,
  `botigues_Id_botiga` INT NOT NULL,
  `botigues_Comandes_Id_Comanda` INT NOT NULL,
  `botigues_Id_botiga1` INT NOT NULL,
  PRIMARY KEY (`Id_empleat`, `botigues_Id_botiga`, `botigues_Comandes_Id_Comanda`),
  INDEX `fk_Empleats_botigues1_idx` (`botigues_Id_botiga` ASC) VISIBLE,
  UNIQUE INDEX `Id_empleat_UNIQUE` (`Id_empleat` ASC) VISIBLE,
  UNIQUE INDEX `Nom_UNIQUE` (`Nom` ASC) VISIBLE,
  UNIQUE INDEX `Cognoms_UNIQUE` (`Cognoms` ASC) VISIBLE,
  UNIQUE INDEX `NIF_UNIQUE` (`NIF` ASC) VISIBLE,
  UNIQUE INDEX `Telefon_UNIQUE` (`Telefon` ASC) VISIBLE,
  UNIQUE INDEX `botigues_Id_botiga_UNIQUE` (`botigues_Id_botiga` ASC) VISIBLE,
  UNIQUE INDEX `botigues_Comandes_Id_Comanda_UNIQUE` (`botigues_Comandes_Id_Comanda` ASC) VISIBLE,
  UNIQUE INDEX `botigues_Id_botiga1_UNIQUE` (`botigues_Id_botiga1` ASC) VISIBLE,
  CONSTRAINT `fk_Empleats_botigues1`
    FOREIGN KEY (`botigues_Id_botiga`)
    REFERENCES `mydb`.`botigues` (`Id_botiga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`productes_comanda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`productes_comanda` (
  `id_comanda` INT NOT NULL,
  `id_producto` INT NOT NULL,
  `Comandes_id` INT NOT NULL,
  `productes_comanda` INT NOT NULL,
  UNIQUE INDEX `id_comanda_UNIQUE` (`id_comanda` ASC) VISIBLE,
  INDEX `fk_id_producto_idx` (`id_producto` ASC) VISIBLE,
  PRIMARY KEY (`Comandes_id`),
  CONSTRAINT `fk_id_comanda`
    FOREIGN KEY (`id_comanda`)
    REFERENCES `mydb`.`Comandes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_producto`
    FOREIGN KEY (`id_producto`)
    REFERENCES `mydb`.`Comandes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productes_comanda_Comandes1`
    FOREIGN KEY (`Comandes_id`)
    REFERENCES `mydb`.`Comandes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
