-- MySQL Script generated by MySQL Workbench
-- Wed May 28 00:22:23 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Proveidors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Proveidors` (
  `idProveidors` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NOT NULL COMMENT '\n',
  `Adreça` VARCHAR(45) NOT NULL,
  `Telefon` INT NOT NULL,
  `Fax` INT NULL,
  `NIF` INT NOT NULL,
  PRIMARY KEY (`idProveidors`),
  UNIQUE INDEX `Nom_Proveidor_UNIQUE` (`Nom` ASC) VISIBLE,
  UNIQUE INDEX `NIF_Proveidor_UNIQUE` (`NIF` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clients` (
  `idClients` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NOT NULL COMMENT '\n',
  `Adreça` VARCHAR(45) NULL,
  `Telefon` INT NOT NULL,
  `EMAIL` VARCHAR(255) NULL,
  `Data_Registre` DATETIME NOT NULL,
  `Embajador` VARCHAR(255) NULL,
  PRIMARY KEY (`idClients`),
  CONSTRAINT `Embajador`
    FOREIGN KEY (`idClients`)
    REFERENCES `mydb`.`Clients` (`idClients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ulleres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ulleres` (
  `idUlleres` INT NOT NULL AUTO_INCREMENT,
  `Marca` VARCHAR(255) NOT NULL,
  `Graduacio_VE` FLOAT NULL COMMENT 'Graduación Vidre Esqueere',
  `Graduacio_VD` FLOAT NULL,
  `Color_Montura` VARCHAR(45) NOT NULL,
  `Tipus_Montura` ENUM('flotant', 'pasta', 'metàl·lica') NOT NULL,
  `Color_VE` VARCHAR(45) NOT NULL,
  `Color_VD` VARCHAR(45) NOT NULL,
  `Preu` FLOAT NOT NULL,
  `Proveidors_idProveidors` INT NOT NULL,
  `Proveidors_idProveidors1` INT NOT NULL,
  PRIMARY KEY (`idUlleres`),
  INDEX `fk_Ulleres_Proveidors1_idx` (`Proveidors_idProveidors1` ASC) VISIBLE,
  CONSTRAINT `fk_Ulleres_Proveidors1`
    FOREIGN KEY (`Proveidors_idProveidors1`)
    REFERENCES `mydb`.`Proveidors` (`idProveidors`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Venedors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Venedors` (
  `Nom` VARCHAR(45) NOT NULL,
  `ID_Venedor` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`ID_Venedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Venda` (
  `Venta_ID` INT NOT NULL AUTO_INCREMENT,
  `Data_Venda` DATETIME NOT NULL,
  `Venedors_Nom_Id` INT NOT NULL,
  `Clients_idClients` INT NOT NULL,
  `Ulleres_idUlleres` INT NOT NULL,
  `Ulleres_Proveidors_idProveidors` INT NOT NULL,
  PRIMARY KEY (`Venta_ID`),
  INDEX `fk_Venda_Venedors_idx` (`Venedors_Nom_Id` ASC) VISIBLE,
  INDEX `fk_Venda_Clients1_idx` (`Clients_idClients` ASC) VISIBLE,
  INDEX `fk_Venda_Ulleres1_idx` (`Ulleres_idUlleres` ASC, `Ulleres_Proveidors_idProveidors` ASC) VISIBLE,
  CONSTRAINT `fk_Venda_Venedors`
    FOREIGN KEY (`Venedors_Nom_Id`)
    REFERENCES `mydb`.`Venedors` (`ID_Venedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venda_Clients1`
    FOREIGN KEY (`Clients_idClients`)
    REFERENCES `mydb`.`Clients` (`idClients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venda_Ulleres1`
    FOREIGN KEY (`Ulleres_idUlleres` , `Ulleres_Proveidors_idProveidors`)
    REFERENCES `mydb`.`Ulleres` (`idUlleres` , `Proveidors_idProveidors`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
